listen:
  address: 0.0.0.0
  port: 4040
namespace:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
    source_files:
      - /var/log/nginx/access.log
    labels:
      instance: ${HOSTNAME}
